name: DemoNewCD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!


  deploy-dev:
    runs-on: self-hosted
    environment: 
      name: desenvolvimento
      url: 'julioarruda.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev

  deploy-hmg:
    runs-on: self-hosted
    environment: 
      name: homologacao
      url: 'julioarruda.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HMG


  deploy-prd:
    runs-on: self-hosted
    environment: 
      name: producao
      url: 'julioarruda.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD

